'use strict';

const COUNTRIES = [
  { code: 'NG', name: 'Nigeria', dial: '+234' },
  { code: 'GH', name: 'Ghana', dial: '+233' },
  { code: 'KE', name: 'Kenya', dial: '+254' },
  { code: 'ZA', name: 'South Africa', dial: '+27' },
  { code: 'US', name: 'United States', dial: '+1' },
  { code: 'GB', name: 'United Kingdom', dial: '+44' },
  { code: 'CA', name: 'Canada', dial: '+1' },
  { code: 'IE', name: 'Ireland', dial: '+353' },
  { code: 'FR', name: 'France', dial: '+33' },
  { code: 'DE', name: 'Germany', dial: '+49' },
  { code: 'IT', name: 'Italy', dial: '+39' },
  { code: 'ES', name: 'Spain', dial: '+34' },
  { code: 'NL', name: 'Netherlands', dial: '+31' },
  { code: 'BE', name: 'Belgium', dial: '+32' },
  { code: 'PT', name: 'Portugal', dial: '+351' },
  { code: 'SE', name: 'Sweden', dial: '+46' },
  { code: 'NO', name: 'Norway', dial: '+47' },
  { code: 'DK', name: 'Denmark', dial: '+45' },
  { code: 'FI', name: 'Finland', dial: '+358' },
  { code: 'CH', name: 'Switzerland', dial: '+41' },
  { code: 'AT', name: 'Austria', dial: '+43' },
  { code: 'PL', name: 'Poland', dial: '+48' },
  { code: 'UA', name: 'Ukraine', dial: '+380' },
  { code: 'TR', name: 'Turkey', dial: '+90' },
  { code: 'AE', name: 'United Arab Emirates', dial: '+971' },
  { code: 'SA', name: 'Saudi Arabia', dial: '+966' },
  { code: 'QA', name: 'Qatar', dial: '+974' },
  { code: 'IN', name: 'India', dial: '+91' },
  { code: 'PK', name: 'Pakistan', dial: '+92' },
  { code: 'BD', name: 'Bangladesh', dial: '+880' },
  { code: 'CN', name: 'China', dial: '+86' },
  { code: 'JP', name: 'Japan', dial: '+81' },
  { code: 'KR', name: 'South Korea', dial: '+82' },
  { code: 'SG', name: 'Singapore', dial: '+65' },
  { code: 'MY', name: 'Malaysia', dial: '+60' },
  { code: 'ID', name: 'Indonesia', dial: '+62' },
  { code: 'PH', name: 'Philippines', dial: '+63' },
  { code: 'AU', name: 'Australia', dial: '+61' },
  { code: 'NZ', name: 'New Zealand', dial: '+64' },
  { code: 'BR', name: 'Brazil', dial: '+55' },
  { code: 'MX', name: 'Mexico', dial: '+52' },
  { code: 'AR', name: 'Argentina', dial: '+54' },
  { code: 'EG', name: 'Egypt', dial: '+20' },
  { code: 'MA', name: 'Morocco', dial: '+212' },
  { code: 'DZ', name: 'Algeria', dial: '+213' },
  { code: 'TN', name: 'Tunisia', dial: '+216' },
  { code: 'CM', name: 'Cameroon', dial: '+237' },
  { code: 'CI', name: "Côte d'Ivoire", dial: '+225' },
  { code: 'SN', name: 'Senegal', dial: '+221' },
  { code: 'TG', name: 'Togo', dial: '+228' },
  { code: 'BJ', name: 'Benin', dial: '+229' },
  { code: 'NE', name: 'Niger', dial: '+227' },
  { code: 'TD', name: 'Chad', dial: '+235' },
  { code: 'ML', name: 'Mali', dial: '+223' },
  { code: 'BF', name: 'Burkina Faso', dial: '+226' },
  { code: 'GN', name: 'Guinea', dial: '+224' },
  { code: 'SL', name: 'Sierra Leone', dial: '+232' },
  { code: 'LR', name: 'Liberia', dial: '+231' },
  { code: 'GM', name: 'Gambia', dial: '+220' },
  { code: 'ET', name: 'Ethiopia', dial: '+251' },
  { code: 'UG', name: 'Uganda', dial: '+256' },
  { code: 'TZ', name: 'Tanzania', dial: '+255' },
  { code: 'RW', name: 'Rwanda', dial: '+250' },
  { code: 'ZW', name: 'Zimbabwe', dial: '+263' },
  { code: 'ZM', name: 'Zambia', dial: '+260' },
  { code: 'AO', name: 'Angola', dial: '+244' },
  { code: 'CD', name: 'DR Congo', dial: '+243' },
  { code: 'JM', name: 'Jamaica', dial: '+1876' },
  { code: 'TT', name: 'Trinidad and Tobago', dial: '+1868' },
  { code: 'HT', name: 'Haiti', dial: '+509' },
];

const byCode = Object.fromEntries(COUNTRIES.map((c) => [c.code, c]));

function isValidCountry(code) {
  return Boolean(byCode[String(code || '').toUpperCase()]);
}

module.exports = { COUNTRIES, isValidCountry };
